name: Deploy to Snowflake

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SnowSQL
        uses: snowflakedb/snowflake-actions/setup-snowsql@main

      - name: Configure SnowSQL connection
        run: |
          mkdir -p ~/.snowsql
          cat <<EOF > ~/.snowsql/config
          [connections.my_conn]
          accountname = ${{ secrets.SNOWFLAKE_ACCOUNT }}
          username = ${{ secrets.SNOWFLAKE_USER }}
          password = ${{ secrets.SNOWFLAKE_PASSWORD }}
          warehousename = ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          dbname = ${{ secrets.SNOWFLAKE_DATABASE }}
          schemaname = ${{ secrets.SNOWFLAKE_SCHEMA }}
          rolename = ${{ secrets.SNOWFLAKE_ROLE }}
          EOF

      - name: Run SQL Script
        run: |
          snowsql -c my_conn -f schemas/ff_schema.sql