name: Deploy to Snowflake

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libc6 libncurses6 libxml2 libssl3 ca-certificates

      - name: Download & Install SnowSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          curl -s https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/install | bash -s -- -y
          echo "$HOME/.snowsql" >> $GITHUB_PATH
          ~/.snowsql/snowsql --version

      - name: Configure SnowSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip

          # Download verified working install script (v1.2.24)
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-linux_x86_64.bash

          # Make it executable and install
          chmod +x snowsql-linux_x86_64.bash
          ./snowsql-linux_x86_64.bash -y -d $HOME/snowsql

          # Add snowsql to PATH for GitHub runner
          echo "$HOME/snowsql" >> $GITHUB_PATH
          echo "::add-path::$HOME/snowsql"

          # Verify installation
          $HOME/snowsql/snowsql --version

      - name: Run SQL Script
        run: |
          $HOME/snowsql/snowsql -c my_conn -f schemas/ff_schema.sql
