name: Deploy to Snowflake

on:
  push:
    branches:
      - master  # or "main", depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install SnowSQL CLI
        run: |
          pip install --upgrade pip
          pip install snowflake-cli-labs
          

      - name: Run SnowSQL script
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          snowflake -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASSWORD \
            -d MYDB -s FF_SCHEMA -r ACCOUNTADMIN \
            -f schemas/ff_schema.sql
