jobs:
  deploy:
    container:
      image: snowflake/snowsql:latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure and Run
        run: |
          mkdir -p ~/.snowsql
          cat <<EOF > ~/.snowsql/config
          [connections.my_conn]
          accountname = ${{ secrets.SNOWFLAKE_ACCOUNT }}
          username = ${{ secrets.SNOWFLAKE_USER }}
          password = ${{ secrets.SNOWFLAKE_PASSWORD }}
          warehousename = ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          dbname = ${{ secrets.SNOWFLAKE_DATABASE }}
          schemaname = ${{ secrets.SNOWFLAKE_SCHEMA }}
          rolename = ${{ secrets.SNOWFLAKE_ROLE }}
          EOF
          
          snowsql -c my_conn -f schemas/ff_schema.sql