name: Deploy to Snowflake

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Snowflake CLI (new)
        run: pip install snowflake-cli-labs

      - name: Run Snowflake SQL script
        run: |
          snowflake sql -f schemas/ff_schema.sql \
            -a ${{ secrets.SNOWFLAKE_ACCOUNT }} \
            -u ${{ secrets.SNOWFLAKE_USER }} \
            -p ${{ secrets.SNOWFLAKE_PASSWORD }} \
            --role ${{ secrets.SNOWFLAKE_ROLE }} \
            --warehouse ${{ secrets.SNOWFLAKE_WAREHOUSE }} \
            --database ${{ secrets.SNOWFLAKE_DATABASE }} \
            --schema ${{ secrets.SNOWFLAKE_SCHEMA }}
