name: Deploy to Snowflake

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SnowSQL CLI
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-linux_x86_64.bash
          bash snowsql-linux_x86_64.bash -y
          echo "$HOME/.snowsql" >> $GITHUB_PATH

      - name: Configure SnowSQL connection
        run: |
          mkdir -p ~/.snowsql
          cat <<EOF > ~/.snowsql/config
          [connections.my_conn]
          accountname = ${{ secrets.SNOWFLAKE_ACCOUNT }}
          username = ${{ secrets.SNOWFLAKE_USER }}
          password = ${{ secrets.SNOWFLAKE_PASSWORD }}
          warehousename = ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          dbname = ${{ secrets.SNOWFLAKE_DATABASE }}
          schemaname = ${{ secrets.SNOWFLAKE_SCHEMA }}
          rolename = ${{ secrets.SNOWFLAKE_ROLE }}
          EOF

      - name: Run SQL Script
        run: |
          snowsql -c my_conn -f schemas/ff_schema.sql
