name: Deploy to Snowflake

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libc6 libncurses6 libxml2 libssl3 ca-certificates

      - name: Download & Install SnowSQL
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          curl -s https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/install | bash -s -- -y
          echo "$HOME/.snowsql" >> $GITHUB_PATH
          ~/.snowsql/snowsql --version

      - name: Configure SnowSQL
        run: |
          mkdir -p ~/.snowsql
          cat <<EOF > ~/.snowsql/config
          [connections.my_conn]
          accountname = ${{ secrets.SNOWFLAKE_ACCOUNT }}
          username = ${{ secrets.SNOWFLAKE_USER }}
          password = ${{ secrets.SNOWFLAKE_PASSWORD }}
          warehousename = ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          dbname = ${{ secrets.SNOWFLAKE_DATABASE }}
          schemaname = ${{ secrets.SNOWFLAKE_SCHEMA }}
          rolename = ${{ secrets.SNOWFLAKE_ROLE }}
          EOF

      - name: Run SQL Script
        run: |
          ~/.snowsql/snowsql -c my_conn -f schemas/ff_schema.sql
